### ISSUE TITLE
I don't see the "Save and Share Project" option on the context menu

### ISSUE THREAD

**Issue by tchia04** [SmartBear/ready-git-plugin#9]
I am using SoapUI 5.1.2 pro and I have changed composite to true
But I don't see any "Save and Share project" option when right clicking on a project. 

Is this plugin not supported on SoapUI 5.1.2 Pro ?

**Comment by prakashmrec** [comment]
Unfortunately it is not. Git plugin works with Ready! API only.

**Comment by tchia04** [comment]
Is it a easy migration to go from SoapUI pro to Ready API ?  Do I need to get a different license or can I use the same license ?  Is there some document on the things to watch out for when migrating ?

**Comment by prakashmrec** [comment]
There is no need for a new license. You can use Ready! API with SoapUI Pro license.

Here is guide about the migration from SoapUI to Ready! API: http://readyapi.smartbear.com/soapui/intro/moving
